# =============================================================================
# VELIRA AUTO-REMEDIATION — CRITICAL DRIFT DETECTED
# Generated by Velira GxP Compliance Engine
# =============================================================================
#
# Resource:  genomics-data-storage-prod
# Severity:  CRITICAL
# Detected:  2026-03-01T16:35:51Z
# Baseline:  v3.2 (validated 2025-11-15)
# Reference: 21 CFR Part 11.10(a)
# =============================================================================

resource "azurerm_storage_account" "genomics_data" {
  name                     = "genomicsdatastorageprod"
  resource_group_name      = azurerm_resource_group.gxp_prod.name
  location                 = "eastus"
  account_tier             = "Standard"
  account_replication_type = "GRS"

  # CRITICAL FIX: Re-enable encryption (was disabled — GxP violation)
  blob_properties {
    versioning_enabled = true
  }

  # CRITICAL FIX: Disable public access (was enabled — data exposure)
  allow_nested_items_to_be_public = false

  # CRITICAL FIX: Enforce TLS 1.2 minimum (was downgraded to TLS 1.0)
  min_tls_version = "TLS1_2"

  # CRITICAL FIX: Enforce HTTPS only (was disabled — plaintext exposure)
  https_traffic_only_enabled = true

  # CRITICAL FIX: Restore network firewall (was set to Allow all)
  network_rules {
    default_action             = "Deny"
    virtual_network_subnet_ids = [azurerm_subnet.data_subnet.id]
    bypass                     = ["AzureServices"]
  }

  tags = {
    environment   = "gxp-prod"
    compliance    = "21-CFR-Part-11"
    velira_fix_id = "5d39777b"
  }
}
